
name: inference-test

on:
  push:
  workflow_dispatch:

jobs:
  run-amd64:
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Pip setup
        run: |
          python -m pip install --upgrade pip
          pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
          pip install fastai

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y git-lfs
          git lfs install

      - name: Prepare environment
        run: |
          git clone https://huggingface.co/ninjalabo/resnet18 && cp resnet18/model.pkl md/model.pkl
          git clone https://huggingface.co/datasets/ninjalabo/imagenette2-320 data
          cd data && git lfs pull

      - name: Run tests
        run: python test_all.py amd64
